on:
  schedule:
    - cron: '0 11 * * *' # 매일 UTC 4시 = KST 13시
  workflow_dispatch: # 수동 실행도 가능하게

jobs:
  single-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up git config
        run: |
          git config --global user.email "aa"
          git config --global user.name "aa"

      - name: Pull latest changes
        run: git pull --rebase

      - name: Make empty commit with KST date
        run: |
          export TZ=Asia/Seoul  # 시간대를 한국 표준시(KST)로 지정
          git commit --allow-empty --date="$(date '+%a %b %d %H:%M:%S %Y +0900')" -m "auto commit $(date '+%Y-%m-%d %H:%M:%S')"  # 빈 커밋 생성(중복 방지 위해 메시지에 타임스탬프 포함), 커밋 날짜를 한국 시간 기준으로 지정
          git push  # 원격 저장소로 푸시(GITHUB_TOKEN 인증 사용)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}